server:
  port: 80



spring:
  # thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  # 데이터 소스
  datasource:
    hikari:
      write:
        jdbc-url: 'jdbc:h2:tcp://localhost/~/test'
        username: sa
        driver-class-name: org.h2.Driver
      read:
        jdbc-url: 'jdbc:h2:tcp://localhost/~/test'
        username: sa
        #password: '1234'
        driver-class-name: org.h2.Driver
  jpa:
    show-sql: true # 콘솔로그로 출력하려면
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
      generate-ddl: true
    properties:
      hibernate:
        batch_fetch_style: PADDED # hibernate 6 부터 deprecated됨..
        default_batch_fetch_size: 100
        format_sql: true # SQL 포맷팅
        highlight_sql: true # ANSI 코드에 색을 나타낸다
        #use_sql_comments: true # SQL 내부에 /* */ 주석 추가


# H2 Console 설정
#h2:
#  console: # H2 DB를 웹에서 관리할 수 있는 기능
#    enabled: true           # H2 Console 사용 여부
#    path: /h2-console       # H2 Console 접속 주소
#  # JPA 설정
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
